version: '3'

services:
  java-app:
    image: java_app
    environment:
      - DB_USER=root
      - DB_PWD=${MYSQL_ROOT_PASSWORD}
      - DB_SERVER=mysql
      - DB_NAME=${MYSQL_DATABASE}
    ports:
      - 8080:8080
    container_name: my-java-app
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  myadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    links: 
       - mysql
    ports:
       - 8081:80
  
volumes:
  mysql-data:
    driver: local

